services:
  - type: web
    name: tributario-backend
    env: python
    plan: starter
    rootDir: backend_fastapi

    buildCommand: |
      poetry install --no-interaction --no-root

    startCommand: |
      poetry run uvicorn backend_fastapi.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
